force-app/main/default/objects/Timeline_Event__c/Timeline_Event__c.object-meta.xml
<CustomObject>
    <label>Timeline Event</label>
    <nameField>
        <displayFormat>TE-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Timeline Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline_Event__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <label>Parent Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Event__c/fields/Timeline_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Timeline_Event_Type__c</fullName>
    <label>Timeline Event Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timeline_Event_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timeline_Event_Message__e/Timeline_Event_Message__e.object-meta.xml
<CustomObject>
    <label>Timeline Event Message</label>
    <pluralLabel>Timeline Event Messages</pluralLabel>
</CustomObject>

force-app/main/default/objects/Timeline_Event_Message__e/fields/Event_Object_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Object_Id__c</fullName>
    <label>Event Object Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Event_Message__e/fields/Timeline_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Timeline_Event_Type__c</fullName>
    <label>Timeline Event Type</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Event_Type__mdt/Timeline_Event_Type__mdt.object-meta.xml
<CustomObject>
    <description>Specifies schema for different timeline event types</description>
    <label>Timeline Event Type</label>
    <pluralLabel>Timeline Event Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Timeline_Event_Type__mdt/fields/Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Api_Name__c</fullName>
    <inlineHelpText>The api name of the object this timeline event is related to.</inlineHelpText>
    <label>Object Api Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Event_Type__mdt/fields/Path_to_Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Path_to_Parent_Id__c</fullName>
    <inlineHelpText>Path to the parent id relative to the Object Api Name.</inlineHelpText>
    <label>Path to Parent Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Event_Type_Field__mdt/Timeline_Event_Type_Field__mdt.object-meta.xml
<CustomObject>
    <description>Information about specific fields for a Timeline Event Type</description>
    <label>Timeline Event Type Field</label>
    <pluralLabel>Timeline Event Type Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Timeline_Event_Type_Field__mdt/fields/Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Api_Name__c</fullName>
    <description>API Name of the field. This is relative to the Object Api Name of the Timeline Event Type.</description>
    <label>Api Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Event_Type_Field__mdt/fields/Timeline_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Timeline_Event_Type__c</fullName>
    <label>Timeline Event Type</label>
    <referenceTo>Timeline_Event_Type__mdt</referenceTo>
    <relationshipLabel>Timeline Event Type Fields</relationshipLabel>
    <relationshipName>Timeline_Event_Type_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/globalValueSets/Timeline_Event_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contact_Updated</fullName>
        <label>Contact Updated</label>
    </customValue>
    <masterLabel>Timeline Event Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TimelineEventMessageTriggerHandler.cls
public without sharing class TimelineEventMessageTriggerHandler 
{
    private static List<Timeline_Event_Message__e> messageList
    {
        get { return (List<Timeline_Event_Message__e>)Trigger.new; }
    }

    private static Map<String,Timeline_Event_Type_Field__mdt> fieldMap = Timeline_Event_Type_Field__mdt.getAll();

    public static void CreateTimelineEvents() 
    {
        List<Timeline_Event__c> timelineEventList = new List<Timeline_Event__c>();
        for(Timeline_Event_Message__e message : messageList) {
            Timeline_Event_Type__mdt eventTypeObj = Timeline_Event_Type__mdt.getInstance(message.Timeline_Event_Type__c);
            List<Timeline_Event_Type_Field__mdt> fieldList = getFields(eventTypeObj);

            Id objId = message.Event_Object_Id__c;
            Set<string> fieldSet = new Set<string>();
            fieldSet.add(eventTypeObj.Path_to_Parent_Id__c);
            for(Timeline_Event_Type_Field__mdt fieldObj : fieldList) {
                fieldSet.add(fieldObj.Api_Name__c);
            }
            string query = 
                'select ' + String.join(new List<string>(fieldSet), ', ')
                + ' from ' + eventTypeObj.Object_Api_Name__c
                + ' where Id = :objId';
            List<SObject> objList = Database.query(query);
            if (objList.isEmpty()) {
                continue;
            }
            SObject obj = objList[0];

            Timeline_Event__c timelineEventObj = new Timeline_Event__c(
                Timeline_Event_Type__c = message.Timeline_Event_Type__c,
                Parent_Id__c = (string)obj.get(eventTypeObj.Path_to_Parent_Id__c)
            );
            Map<String,Object> contentMap = new Map<String,List<Map<String,Object>>>();
            List<Object> contentFieldList = new List<Map<String,Object>>();
            contentMap.put('fields',contentFieldList);
            for(Timeline_Event_Type_Field__mdt fieldObj : fieldList) {
                Map<String,Object> contentFieldMap = new Map<String,Object>();
                contentFieldMap.put('Name', fieldObj.Label);
                contentFieldMap.put('Value', obj.get(fieldObj.Api_Name__c));
                contentFieldMap.put('Order', fieldObj.Order__c);
                contentFieldList.add(contentFieldMap);
            }
            timelineEventObj.Content__c = JSON.serialize(contentMap);
            timelineEventList.add(timelineEventObj);
        }
        insert timelineEventList;
    }

    private static List<Timeline_Event_Type_Field__mdt> getFields(Timeline_Event_Type__mdt eventTypeObj) {
        List<Timeline_Event_Type_Field__mdt> fieldList = new List<Timeline_Event_Type_Field__mdt>();
        for(Timeline_Event_Type_Field__mdt fieldObj : fieldMap.values()) {
            if (fieldObj.Timeline_Event_Type__c == eventTypeObj.Id) {
                fieldList.add(fieldObj);
            }
        }
        return fieldList;
    }
}