force-app/main/default/objects/Timeline_Event__c/Timeline_Event__c.object-meta.xml
<CustomObject>
    <label>Timeline Event</label>
    <nameField>
        <displayFormat>TE-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Timeline Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timeline_Event__c/fields/Timeline_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Timeline_Event_Type__c</fullName>
    <label>Timeline Event Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Timeline_Event_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timeline_Event_Message__e/Timeline_Event_Message__e.object-meta.xml
<CustomObject>
    <label>Timeline Event Message</label>
    <pluralLabel>Timeline Event Messages</pluralLabel>
</CustomObject>

force-app/main/default/objects/Timeline_Event_Message__e/fields/Event_Object_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Object_Id__c</fullName>
    <label>Event Object Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timeline_Event_Message__e/fields/Timeline_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Timeline_Event_Type__c</fullName>
    <label>Timeline Event Type</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Timeline_Event_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contact_Updated</fullName>
        <label>Contact Updated</label>
    </customValue>
    <masterLabel>Timeline Event Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TimelineEventMessageTriggerHandlerTest.cls
@IsTest
public class TimelineEventMessageTriggerHandlerTest 
{
    @IsTest
    static void OnInsert_CreatePlatformEventMessage() 
    {
        Contact contactObj = new Contact(
            FirstName = 'First',
            LastName = 'Last',
            MobilePhone = '1234567890'
        );
        insert contactObj;

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(new Timeline_Event_Message__e (
            Timeline_Event_Type__c = 'Contact_Updated',
            Event_Object_Id__c = contactObj.Id
        ));
        Test.stopTest();

        List<Timeline_Event__c> timelineEventList = [select Id from Timeline_Event__c];
        System.assertEquals(1, timelineEventList.size(), 'Timeline Event not created');
    }
}